name: Dab Code Testing
permissions:
  id-token: write
  issues: write
  contents: read
  pull-requests: write
on:
  push:
    branches: [ main ]
    paths:
      - "code/**"
  pull_request:
    types: [opened, synchronize]
jobs:
  deploy:
    name: "Test and deploy bundle"
    runs-on: self-hosted
    environment: test
    defaults:
      run:
        working-directory: ./code
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt -r dev-requirements.txt

      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Run unit tests
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_TST }}
          DATABRICKS_CLUSTER_ID: ${{ vars.DATABRICKS_CLUSTER_ID }}
        run: |
          pytest tests/ 

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy --target test
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_TST }}
          DATABRICKS_BUNDLE_ENV: tst

  validation:
    name: "Run validation"
    runs-on: self-hosted
    environment: test
    defaults:
      run:
        working-directory: ./code

    needs:
      - deploy

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - shell: bash
        name: Run notebook validation
        run: |
          set -o pipefail
          databricks bundle run notebook_validation_job -t test --refresh-all 2>&1 | tee output.log
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_TST }}
          DATABRICKS_BUNDLE_ENV: test
