---
# This is a basic GitHub Actions pipeline to validate Terraform
name: Dab Code Release

on:
  push:
    branches: [ main ]
    paths:
      - "code/**"
jobs:
  release-prod:
    name: "Test and deploy bundle"
    runs-on: self-hosted
    environment: prod
    defaults:
      run:
        working-directory: ./code
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt -r dev-requirements.txt
      - uses: databricks/setup-cli@main
      - run: databricks bundle deploy --target prod
        env:
          DATABRICKS_BUNDLE_ENV: prod
          ARM_CLIENT_ID: ${{ vars.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.AZURE_AD_TENANT_ID }}
  release-dr:
    name: "Test and deploy bundle"
    needs: [release-prod]
    runs-on: self-hosted
    environment: dr
    defaults:
      run:
        working-directory: ./code
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt -r dev-requirements.txt
      - uses: databricks/setup-cli@main
      - run: databricks bundle deploy --target dr
        env:
          DATABRICKS_BUNDLE_ENV: dr
          ARM_CLIENT_ID: ${{ vars.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.AZURE_AD_TENANT_ID }}
